# SPDX-FileCopyrightText: 2025 Ada Freya Ahmed (neptuwunium)
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "scarlet"
license.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
witch-common = { path = "../../witch/common" }

[lib]
name = "scarlet"
crate-type = ["cdylib"]
