# SPDX-FileCopyrightText: 2025 Ada Freya Ahmed (neptuwunium)
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "scarlet"
license.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
witch-common = { path = "../../witch/common" }
flexi_logger = "0"
log = "0"

[lib]
name = "scarlet"
crate-type = ["cdylib"]

[target.'cfg(target_os = "windows")'.dependencies]
hudhook = "0"
windows = { version = "0.54", default-features = false, features = [
	"Foundation",
	"Win32_System", "Win32_System_Threading", "Win32_System_LibraryLoader",
	"Win32_System_SystemServices"
] }
