# SPDX-FileCopyrightText: 2025 Ada Freya Ahmed (neptuwunium)
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "sorcery-introspection"
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
witch = { path = "../../witch/witch" }
witch-common = { path = "../../witch/common", features = ["serde", "minidump"] }
witch-macro = { path = "../../witch/macro" }

anyhow = "1"
colog = "1"
log = "0"
clap = { version = "4", features = ["derive"] }
colored = "3"
env_logger = "0"
serde_json = "1"
