# SPDX-FileCopyrightText: 2025 Ada Freya Ahmed (neptuwunium)
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "witch_macro"
license.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
witch_common = { path = "../common" }

syn = { version = "2", features = ["full"] }
quote = "1"
